layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 1
  exclude:
    archived: false
    forks: false
    projects:
     - go_kraken
     - gobpmnLab
     - gobpmnHash
     - gobpmnReview
     - gobpmnEngine
     - gobpmnModel
     - gobpmnExamples
     - discogs
     - accounting
     - personal-website

social_media:
  hackerrank: salvatore_gonda
  linkedin: sgonda1
  medium: salvatoregonda
  stackoverflow: 9210181
  website: http://salvatore-gonda.de

topics:
  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/go/go.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png
