layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 3
  exclude:
    archived: false
    forks: false
    projects:
     - go_kraken
     - gobpmnLab
     - gobpmnHash
     - gobpmnReview
     - gobpmnEngine
     - gobpmnModel
     - gobpmnExamples
     - discogs
     - accounting
     - personal-website

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: salvatore_gonda
  # instagram: your_username
  # keybase: your_username
  linkedin: sgonda1
  # mastodon: your_username
  medium: salvatoregonda
  stackoverflow: 9210181
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://salvatore-gonda.de
  # youtube: your_username

topics:
  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/go/go.png

  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/rust/rust.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/java/java.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
